### ISSUE TITLE
Undefined name 'midi_link' in get_mozart.py

### ISSUE THREAD

**Issue by cclauss** [piyush-kgp/Music-Generation-with-deep-learning#1]
[flake8](http://flake8.pycqa.org) testing of https://github.com/piyush-kgp/Music-Generation-with-deep-learning on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./piano_music_generation_seq2seq/get_mozart.py:22:40: F821 undefined name 'midi_link'
            urllib.request.urlretrieve(midi_link, file_path)
                                       ^
1     F821 undefined name 'midi_link'
1
```

**Comment by piyush01123** [comment]
This is resolved now. Thanks @cclauss. Really appreciate it.
